package com.gigwager.service;

import com.gigwager.model.DriverShiftReport;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class DriverShiftReportService {

    private final List<DriverShiftReport> reports = List.of(
            new DriverShiftReport(
                    "doordash",
                    "benchmark",
                    "National DoorDash field test",
                    "US",
                    "Field test",
                    "mixed lunch/dinner",
                    "$86 gross over 6.5 hours and 90 miles",
                    86.0,
                    6.5,
                    6.5,
                    90,
                    null,
                    "This is the cleanest public reminder that gross payout and take-home pay are different numbers once mileage is counted.",
                    "NerdWallet DoorDash pay test",
                    "https://www.nerdwallet.com/finance/learn/how-much-does-doordash-pay"),
            new DriverShiftReport(
                    "doordash",
                    "benchmark",
                    "Suburban six-shift week",
                    "US",
                    "Reddit self-report",
                    "six lunch and dinner shifts",
                    "$847 gross, 312 miles, about 28-30 hours, roughly $526 net claimed",
                    847.0,
                    29.0,
                    null,
                    312,
                    null,
                    "The driver counted mileage and self-employment tax instead of treating the app payout as take-home pay. The post is self-reported and the thread debates the cost model.",
                    "DoorDash $847 weekly net breakdown",
                    "https://www.reddit.com/r/doordash_drivers/comments/1skp7eb/doordash_said_i_made_847_last_week_heres_what_i/"),
            new DriverShiftReport(
                    "doordash",
                    "benchmark",
                    "Multi-app March report",
                    "US",
                    "Reddit self-report",
                    "14-16 hours per day across multiple apps",
                    "$13,000+ gross, 8,013 miles, $540 gas, $134 maintenance",
                    13000.0,
                    465.0,
                    null,
                    8013,
                    null,
                    "This is an upside case across DoorDash, Uber Eats, and Instacart, with an extreme schedule. It should not be presented as a normal DoorDash-only benchmark.",
                    "DoorDash multi-app March earnings report",
                    "https://www.reddit.com/r/doordash_drivers/comments/1s9yuq2/i_made_13000_in_march/"),
            new DriverShiftReport(
                    "doordash",
                    "benchmark",
                    "California full-month report",
                    "CA",
                    "Reddit self-report",
                    "12-14 hours per day, seven days per week",
                    "$8,050.16 monthly payout, 130-190 miles per day, 40 mpg, $300-$380 weekly Prop 22 add-on",
                    8050.16,
                    null,
                    null,
                    null,
                    null,
                    "The post gives a useful California adjustment-pay signal but does not identify a city, so it belongs in the national evidence layer rather than a city ranking.",
                    "DoorDash California first-month wages",
                    "https://www.reddit.com/r/DoorDashDrivers/comments/1tlpx2i/first_full_month_wages/"),
            new DriverShiftReport(
                    "doordash",
                    "benchmark",
                    "Virginia 330-delivery report",
                    "VA",
                    "Reddit self-report",
                    "part-time work alongside a daytime job",
                    "$2,756.45 revenue, $2,225.48 net after listed costs and tax reserve, 330 deliveries",
                    2756.45,
                    137.1,
                    null,
                    null,
                    330,
                    "The driver reports $20.10 per active hour before reserves and $16.52 after tax, oil, and tire budgeting. Active hours are derived from the reported gross hourly figure.",
                    "DoorDash Virginia first-month earnings ledger",
                    "https://www.reddit.com/r/doordash_drivers/comments/1tnjs66/1_month_and_330_deliveries_here_are_real_numbers/"),
            new DriverShiftReport(
                    "doordash",
                    "benchmark",
                    "Illinois $3k week breakdown",
                    "IL",
                    "Reddit self-report",
                    "about 105 hours in one week",
                    "$3,076.68 gross, 2,041.2 miles, roughly $2,335.67 after the poster's tax and gas estimate",
                    3076.68,
                    105.0,
                    null,
                    2041,
                    null,
                    "This is a high-gross week whose own discussion calculates a much lower effective result after taxes, mileage, and gas. Treat the net as the poster's rough estimate, not audited accounting.",
                    "DoorDash Illinois $3k week discussion",
                    "https://www.reddit.com/r/doordash_drivers/comments/1r03paz/i_made_3k_in_a_week/"),
            new DriverShiftReport(
                    "doordash",
                    "benchmark",
                    "Full-cost after-tax benchmark",
                    "US",
                    "Reddit driver discussion",
                    "normal DoorDash driving",
                    "$20 gross/hour versus about $14.50/hour after vehicle costs and tax in one detailed model",
                    null,
                    null,
                    null,
                    null,
                    null,
                    "This is a cost-model benchmark rather than a shift receipt. It shows why net pay can fall below app-reported gross even when gas alone looks manageable.",
                    "DoorDash full-cost net-hourly discussion",
                    "https://www.reddit.com/r/doordash_drivers/comments/1rwa5vp/does_anyone_actually_calculate_their_real/"),
            new DriverShiftReport(
                    "doordash",
                    "benchmark",
                    "Texas 12-hour daily range",
                    "TX",
                    "Reddit self-report",
                    "12-hour day, about 40 orders",
                    "$150-$200 on a typical 12-hour day, with $180-$190 on some weekends",
                    null,
                    12.0,
                    null,
                    null,
                    40,
                    "The driver was actively testing neighboring areas because zone choice changed the result. This is a range report, not a guaranteed daily target.",
                    "Texas DoorDash daily earnings discussion",
                    "https://www.reddit.com/r/doordash_drivers/comments/1u0y0fg/question_about_earnings/"),
            new DriverShiftReport(
                    "doordash",
                    "benchmark",
                    "E-bike 8,000-mile cost report",
                    "US",
                    "Reddit self-report",
                    "about 30 miles per day, five days per week",
                    "8,000 e-bike miles; $1,595 purchase, about $88 maintenance, roughly $3/month charging",
                    null,
                    null,
                    null,
                    8000,
                    null,
                    "This is a vehicle-cost comparison, not an earnings claim. The driver reports far lower operating cost than a car and used DoorDash plus some Uber Eats.",
                    "DoorDash e-bike 8,000-mile cost report",
                    "https://www.reddit.com/r/doordash_drivers/comments/1pi738e/smashed_8000_miles_on_my_ebike_doing_deliveries/"),
            new DriverShiftReport(
                    "doordash",
                    "benchmark",
                    "California Prop 22 weekly report",
                    "CA",
                    "Reddit self-report",
                    "weekly DoorDash work with Prop 22",
                    "About $1,000 weekly earnings plus $150-$160 weekly Prop 22 pay; driver targets $1.80-$2.00 per mile",
                    1000.0,
                    null,
                    null,
                    null,
                    null,
                    "Prop 22 adds a floor but does not make dead miles free. Keep this as a California regulation example, not a national average.",
                    "California DoorDash Prop 22 weekly report",
                    "https://www.reddit.com/r/doordash_drivers/comments/1un4oid/california_dashers_using_prop_22_whats_your/"),
            new DriverShiftReport(
                    "doordash",
                    "atlanta",
                    "Georgia DoorDash sample",
                    "GA",
                    "Driver discussion",
                    "weekly mixed shifts",
                    "$560.31 gross, 74 deliveries, 19h24m active time, 23h39m dash time",
                    560.31,
                    19.4,
                    23.65,
                    null,
                    74,
                    "The active-time number looked much stronger than the all-in dash-time number, so both clocks need to be visible.",
                    "Georgia DoorDash active-time post",
                    "https://www.reddit.com/r/DoorDashDrivers/comments/1r0oqfo/560_week_in_ga_not_atlanta_74_del_19_active_hrs/"),
            new DriverShiftReport(
                    "doordash",
                    "denver",
                    "Denver suburb report",
                    "CO",
                    "Driver discussion",
                    "suburban dashing",
                    "$12-$15/hr around Centennial-style suburban work",
                    null,
                    null,
                    null,
                    null,
                    null,
                    "The useful lesson is not the exact number; it is that suburb mileage and wait time can pull a strong city model down fast.",
                    "Denver DoorDash driver discussion",
                    "https://www.reddit.com/r/doordash_drivers/comments/1j4uofw/is_anybody_dashing_around_denver_area_if_yes_how/"),
            new DriverShiftReport(
                    "doordash",
                    "phoenix",
                    "Phoenix daily-target report",
                    "AZ",
                    "Driver discussion",
                    "slow-market days",
                    "$100/day became hard when order volume slowed",
                    null,
                    null,
                    null,
                    null,
                    null,
                    "A $100 target page needs hours and miles, not motivational copy. Slow volume changes the target math.",
                    "Phoenix DoorDash slowdown discussion",
                    "https://www.reddit.com/r/doordash_drivers/comments/nb6oi7/doordash_been_slow_lately_its_been_hard_to_get/"),
            new DriverShiftReport(
                    "doordash",
                    "san-jose",
                    "San Jose active-time report",
                    "CA",
                    "Driver discussion",
                    "California active-time math",
                    "Prop 22 and active miles change the pay calculation",
                    null,
                    null,
                    null,
                    null,
                    null,
                    "California pages need active-time and waiting-time checks instead of a single gross screenshot.",
                    "San Jose Prop 22 driver discussion",
                    "https://www.reddit.com/r/doordash_drivers/comments/p5m8is/minimum_wage_ca/"),
            new DriverShiftReport(
                    "doordash",
                    "dallas",
                    "DFW dollar-per-mile report",
                    "TX",
                    "Driver discussion",
                    "spread-out metro orders",
                    "Drivers discuss dollar-per-mile floors before accepting DoorDash orders",
                    null,
                    null,
                    null,
                    null,
                    null,
                    "In DFW, home-to-home miles matter more than restaurant-to-dropoff miles because zone crossings can eat the shift.",
                    "DoorDash dollar-per-mile discussion",
                    "https://www.reddit.com/r/doordash_drivers/comments/1s39uhj/whats_your_minimum_mile_to_accept_doordash_orders/"),
            new DriverShiftReport(
                    "doordash",
                    "minneapolis",
                    "Minnesota suburb report",
                    "MN",
                    "Driver discussion",
                    "suburb comparison",
                    "Drivers compare Saint Paul, Woodbury, White Bear, and Eagan against downtown friction",
                    null,
                    null,
                    null,
                    null,
                    null,
                    "Local zone choice can beat a citywide average when parking and downtown wait time are the real bottleneck.",
                    "Minnesota DoorDash market discussion",
                    "https://www.reddit.com/r/doordash_drivers/comments/14u1c5e/does_anyone_dash_in_minnesota_i_moved_from/"),
            new DriverShiftReport(
                    "uber",
                    "benchmark",
                    "National Uber field test",
                    "US",
                    "Field test",
                    "rideshare driving",
                    "10 active hours, 10 trips, and 305 miles",
                    null,
                    10.0,
                    null,
                    305,
                    10,
                    "Uber screenshots need a mileage check because a strong fare day can still put heavy depreciation on the car.",
                    "NerdWallet Uber pay test",
                    "https://www.nerdwallet.com/finance/learn/how-much-does-an-uber-driver-make"),
            new DriverShiftReport(
                    "uber",
                    "benchmark",
                    "Tennessee UberX/Lyft year report",
                    "TN",
                    "Reddit self-report",
                    "early-morning and surge-only driving",
                    "$23,611 gross after platform fees and tolls, 18,426 miles, $38 gross/hour, $1.28/mile",
                    23611.0,
                    null,
                    null,
                    18426,
                    null,
                    "The driver used a 2014 Honda Civic and only drove selected surge and early-morning windows. The post does not provide enough verified time detail for a net-hourly estimate.",
                    "Tennessee UberX/Lyft gross earnings report",
                    "https://www.reddit.com/r/uberdrivers/comments/1rbz0l4/how_much_did_you_gross_in_2025_and_how_many_miles/"),
            new DriverShiftReport(
                    "uber",
                    "benchmark",
                    "Uber Eats EV multi-app month",
                    "US",
                    "Reddit self-report",
                    "4-6 peak hours per day across six apps",
                    "$3,400-$4,000 monthly across six apps, with $3-$9 off-peak EV charging",
                    null,
                    null,
                    null,
                    null,
                    null,
                    "This is a multi-app delivery report, not Uber rideshare-only data. The useful evidence is that vehicle type, charging cost, peak-window selection, and app mix materially change the result.",
                    "Uber Eats multi-app EV earnings discussion",
                    "https://www.reddit.com/r/UberEatsDrivers/comments/1p4q3bp/average_hourly_wage_for_ubereats_drivers/"),
            new DriverShiftReport(
                    "uber",
                    "chicago",
                    "Chicago airport and bar-close report",
                    "IL",
                    "Driver discussion",
                    "airport and late-night windows",
                    "Drivers separate airport/business-trip windows from generic all-day driving",
                    null,
                    null,
                    null,
                    null,
                    null,
                    "The city average is less useful than knowing which windows avoid unpaid waiting and weak ride density.",
                    "AskChicago Uber/Lyft summer thread",
                    "https://www.reddit.com/r/AskChicago/comments/1rep6pm/do_chicago_lyftuber_drivers_make_good_money_in/"),
            new DriverShiftReport(
                    "uber",
                    "orlando",
                    "Orlando weekend tourism report",
                    "FL",
                    "Driver discussion",
                    "Friday-Sunday tourism",
                    "Strong weekend gross still needs a fuel-cost check",
                    null,
                    null,
                    null,
                    null,
                    null,
                    "Tourism demand can create good windows, but fuel and I-4 time decide whether the net hourly number holds.",
                    "Orlando Uber weekend earnings discussion",
                    "https://www.reddit.com/r/uberdrivers/comments/somguu/how_much_are_uber_drivers_making_in_orlando_with/"));

    public List<DriverShiftReport> getReportsForApp(String app) {
        return reports.stream()
                .filter(report -> report.app().equals(app))
                .collect(Collectors.toList());
    }

    public List<DriverShiftReport> getReportsForCity(String app, String citySlug) {
        return reports.stream()
                .filter(report -> report.app().equals(app))
                .filter(report -> "benchmark".equals(report.citySlug()) || report.citySlug().equals(citySlug))
                .collect(Collectors.toList());
    }
}
